### ISSUE TITLE
code issues

### ISSUE THREAD

**Issue by hbaniecki** [marissachilds/YellowFeverSpillover#1]
Hi, thanks for data & code for the paper. I am trying to recreate the `pdp` plots and found the following issues:

https://github.com/marissachilds/YellowFeverSpillover/blob/658d8be65044d6ef73bc109a82fa3881879fe475/code/SDM/SDM.R#L49 should be `species_occurrence_data`

https://github.com/marissachilds/YellowFeverSpillover/blob/658d8be65044d6ef73bc109a82fa3881879fe475/code/SDM/SDM.R#L82 `v2` file doesn't exist

EDIT: I found out that the `pdp` plot from the paper was made using the `model_eval.R` script.

**Comment by hbaniecki** [comment]
"1. Unzip the shapefiles in the data/raw directory. They are in the Primates directory and brazil_border_shapefiles directory."
Unzipping the downloaded https://github.com/marissachilds/YellowFeverSpillover/blob/master/data/raw/brazil_border_shapefiles/br_municipios.zip file doesn't work for me.

**Comment by marissachilds** [comment]
Thanks for pointing out these mistakes, the correct files should now be references in 'SDM.R'. Unfortunately access to the shapefile will take a bit more work to sort out, as the large file storage solution I previously had setup is no longer working. For the time being, I can send you those files and let me know if there are others that you're looking for.

**Comment by hbaniecki** [comment]
Thanks, not needed anymore
